development:
  secret_key_base: XXXXXXXXXXXXXXXXX
  google_client_id: 883667117786-nd2t8qutlr4uhghgn6otnb6hcfmvnjrq.apps.googleusercontent.com
  google_client_secret: ieELCCUGq6cp665T_DyoicZt

test:
  secret_key_base: XXXXXXXXXXXXXXXXX
  google_client_id: 883667117786-nd2t8qutlr4uhghgn6otnb6hcfmvnjrq.apps.googleusercontent.com
  google_client_secret: ieELCCUGq6cp665T_DyoicZt